# Actions in this workflow
# https://github.com/BaileyJM02/markdown-to-pdf
# https://github.com/marketplace/actions/add-commit

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'documents/md/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Convert md to pdf
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: documents/md
          output_dir: documents/pdf
          # Default is true, can set to false to only get PDF files
          build_html: false

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: 'documents/pdf'
